### ISSUE TITLE
Synchronised folder has root:root ownership

### ISSUE THREAD

**Issue by ibnunes** [ibnunes/ownMine#1]
**Problem:** When syncing to local storage, ownership becomes `root:root`. This does not allow the service to properly start for lack of privileges.

**Suggestion:** check rsync flags to operate over GID and UID ownership.

**Comment by ibnunes** [comment]
Temporarily fixed with the function `ownmine_fixownership`, used by the `pull` option.
I need to check thoroughly if any other option might need such fix.
With that I'll properly manage this issue through the `rsync` options if possible.

**Comment by PedroCavaleiro** [comment]
On the function `ownmine_fixownership` the `chown` command must be applied recursively. Check pull request #3
